// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApawshZ6k6o-6AixZd_IlstF88l-hKFic',
    appId: '1:536402869719:web:1e7a9cc1ccb54718031f92',
    messagingSenderId: '536402869719',
    projectId: 'chbcantibullying-e7ef9',
    authDomain: 'chbcantibullying-e7ef9.firebaseapp.com',
    storageBucket: 'chbcantibullying-e7ef9.firebasestorage.app',
    measurementId: 'G-GZJQF5DT1V',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD86dPDPS-Ej4Wjg4fwWFv4FvUqZ7qDIS4',
    appId: '1:536402869719:ios:ce4b03cc0c3d1285031f92',
    messagingSenderId: '536402869719',
    projectId: 'chbcantibullying-e7ef9',
    storageBucket: 'chbcantibullying-e7ef9.firebasestorage.app',
    iosClientId: '536402869719-c5li4arnpkg6h92c8jmpi4n2qj2gr46e.apps.googleusercontent.com',
    iosBundleId: 'com.example.staffWebapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD86dPDPS-Ej4Wjg4fwWFv4FvUqZ7qDIS4',
    appId: '1:536402869719:ios:ce4b03cc0c3d1285031f92',
    messagingSenderId: '536402869719',
    projectId: 'chbcantibullying-e7ef9',
    storageBucket: 'chbcantibullying-e7ef9.firebasestorage.app',
    iosClientId: '536402869719-c5li4arnpkg6h92c8jmpi4n2qj2gr46e.apps.googleusercontent.com',
    iosBundleId: 'com.example.staffWebapp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRt2rpisiZcTlou4z2i389fG5BSHKm6c8',
    appId: '1:536402869719:android:92b61a4580e00ee5031f92',
    messagingSenderId: '536402869719',
    projectId: 'chbcantibullying-e7ef9',
    storageBucket: 'chbcantibullying-e7ef9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE2Jc9TaXAbDqFts_L9bjAunW5rXxTYOQ',
    appId: '1:536402869719:web:e749682f075bc635031f92',
    messagingSenderId: '536402869719',
    projectId: 'chbcantibullying-e7ef9',
    authDomain: 'chbcantibullying-e7ef9.firebaseapp.com',
    storageBucket: 'chbcantibullying-e7ef9.firebasestorage.app',
    measurementId: 'G-4BS7TCVKKS',
  );

}