import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:staff_webapp/presentation/pages/login_page.dart';
import 'firebase_options.dart'; // generated by flutterfire configure
import 'di.dart'; // <- this is your setupDependencies file
import 'presentation/pages/resolve_ticket_page.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Setup dependency injection
  setupDependencies();

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Staff Web App',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: LoginPage(), // Start at your page
    );
  }
}
