import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:staff_webapp/presentation/pages/login_page.dart';
import 'firebase_options.dart'; // generated by flutterfire configure
import 'di.dart'; // <- this is your setupDependencies file

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Setup dependency injection
  await setupDependencies();

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Staff Web App',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: LoginPage(), // Start at your page
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Text(
          "✅ Authorized Home Page",
          style: TextStyle(fontSize: 20),
        ),
      ),
    );
  }
}